---
deployment:
  tasks:
    # Tentukan path absolut untuk keamanan
    - export HOME=/home/fwrpaxrd
    - export DEPLOYPATH=/home/fwrpaxrd/public_html/backend

    # 1. Jalankan Composer & Artisan di folder kloning (/home/fwrpaxrd/laravel_app)
    - /usr/local/bin/composer install --no-dev --optimize-autoloader
    - /usr/bin/php artisan config:clear
    - /usr/bin/php artisan route:clear
    - /usr/bin/php artisan view:clear

    # 2. Ini adalah bagian "auto load" file Anda
    # Kita menyinkronkan folder 'public' dari aplikasi ke 'public_html/backend'
    # PENTING: Kita mengecualikan file .htaccess dan index.php
    # karena kita sudah mengaturnya secara manual di 'public_html/backend'
    # agar menunjuk ke /laravel_app (dari diskusi kita sebelumnya).
    - /bin/rsync -a --delete --exclude '.htaccess' --exclude 'index.php' public/ $DEPLOYPATH/
